### ISSUE TITLE
Searching country by countryCode returns the first country found with this countryCode

### ISSUE THREAD

**Issue by MerveGencer** [ibrahimsn98/PhoneNumberKit#3]
Some countries have the same countryCode, e.g:

        Country("gg", "Guernsey", 44),
        Country("im", "Isle of Man", 44),
        Country("je", "Jersey", 44),
        Country("gb", "United Kingdom", 44),

So when attachToInput function is called with the defaultCountry = 44, it returns "Guernsey" since it is the first found in the list. Working with countryCode is not a good idea here. It should've been searched by iso2 code since it is the only unique identifier for countries.

Good to have below 2 functions:

    fun attachToInput(input: TextInputLayout, countryIso2: String) {
        this.input = input
        input.editText?.inputType = InputType.TYPE_CLASS_PHONE
        input.editText?.addTextChangedListener(textWatcher)

        input.isStartIconVisible = true
        input.isStartIconCheckable = true
        input.setStartIconTintList(null)

        // Set initial country
        setCountry(getCountry(countryIso2.trim().toLowerCase(Locale.ENGLISH)) ?: Countries.list[0])
        rawInput = country?.countryCode?.prependPlus()
    }

    private fun getCountry(countryIso2: String?): Country? {
        for (country in Countries.list) {
            if (country.iso2 == countryIso2) {
                return country
            }
        }
        return null
    }

**Comment by ibrahimsn98** [comment]
I have merged the PR, thanks for the contribution.
