### ISSUE TITLE
+1 country code defaults to Canada

### ISSUE THREAD

**Issue by kkl260** [ibrahimsn98/PhoneNumberKit#8]
I set up the layout to default to us `phoneNumberKit.attachToInput(layout, "us")` and it works fine, but if I delete the +1 and start entering a new number that begins with 1 the flag will show the Canada flag. I know they both have the same country code, but if I'm defaulting to US then I think it stands to reason updating the number should show the US flag. 

Some way to override this would be great.

**Comment by kkl260** [comment]
Or possibly once it notices the area code change to the correct flag

**Comment by ibrahimsn98** [comment]
You can use it as `phoneNumberKit.attachToInput(layout, "us")` now. Thank you.

**Comment by amanzan** [comment]
This is still not working
