### ISSUE TITLE
Phone number length not catered for.

### ISSUE THREAD

**Issue by Carrieukie** [ibrahimsn98/PhoneNumberKit#9]
I notice when using this library that the length of the number of digits is not catered for because you can input a phone number with less digits.

**Comment by ibrahimsn98** [comment]
Hello, it should be fixed with [release 2.0.0](https://github.com/ibrahimsn98/PhoneNumberKit/releases/tag/2.0.0)

**Comment by Carrieukie** [comment]
Thanks
